### ISSUE TITLE
Create new art using p5.js

### ISSUE THREAD

**Issue by uneeb123** [Alpha-Labs-Global/blockalizer#67]
### Pre-requisities
Familiarity with p5.js

### Context
We are preparing for genesis 3 of Blockalizer. For reference:
- [this](https://opensea.io/assets/ethereum/0xbe440a8cd331cadb9ab611c6000072beb74b963a/780) is how genesis 1 looked
- [this](https://opensea.io/assets/ethereum/0xbe440a8cd331cadb9ab611c6000072beb74b963a/1564) is how genesis 2 looked
Genesis 2 also introduced animations that won't be the case for genesis 3

### What
Update art for genesis 3 to that it looks as follows:
![Screen Shot 2023-03-07 at 3 19 44 PM](https://user-images.githubusercontent.com/4120628/225409658-6a077508-eb05-4050-9a54-10cedc15e1de.png)

The filled circle should represent 1. And unfilled circle represents 0. Every shape is determined by the block number which is provided as input. Additionally, for aesthetics, some shapes are drawn as half circles. For that, the orientation can be determined via randomization. For example, choose a random number between `[0,1,2]` if 0 then full unfilled circle, if 1 then half unfilled circle facing right, if 2 then half unfilled circle facing left. Feel free to choose your own randomization algorithm. You have flexibility over this component as long as the final image looks visually appealing.  Also, feel free to use generic colors. The art is generated using p5.js library.

### Hints
The art style is determined by [this function](https://github.com/Alpha-Labs-Global/blockalizer/blob/master/src/helper/sketch.ts#L39). You have to create a new sketch style [here](https://github.com/Alpha-Labs-Global/blockalizer/tree/master/src/art-styles). It's invoked from [here](https://github.com/Alpha-Labs-Global/blockalizer/blob/master/src/components/Art.tsx#L106). Note how `BlockInfo` and `BlockNumber` are passed as inputs. You'd have to do something similar. And use that to determine the shape. Consider [this style](https://github.com/Alpha-Labs-Global/blockalizer/blob/master/src/art-styles/colored-triangles.ts) as an inspiration.

**Comment by 0x4007** [comment]
The only unclear part is 

> The filled circle should represent 1. And unfilled circle represents 0. 

Given that new bounty hunters (and myself) are coming in with almost no context, are you suggesting that the block numbers are converted into binary before being rendered as an image?

The significance of `0, 1, 2` must also be clarified for this to make sense to me.

---

Essentially I need to understand:
1. the algorithm's input from the prior examples 
2. the difference between the outputs of the first and second algo permutations
3. how far we can stray with creative freedom for implementing a third permutation

If you can explain those here concisely this bounty can be more appealing.

---

Creative work can be tough to "bountify" because there is a subjective dimension to consider before honoring the bounty as completed. I recommend making success conditions as quantitative as possible. With this, these bounties could be considered as "lower risk" (i.e. success conditions are not ambiguous) for experienced developers and might be more attractive to take on.

**Comment by uneeb123** [comment]
>  are you suggesting that the block numbers are converted into binary before being rendered as an image?

Block number is converted into binary [here](https://github.com/Alpha-Labs-Global/blockalizer/blob/master/src/helper/sketch.ts#L135).

> Creative work can be tough to "bountify" because there is a subjective dimension to consider before honoring the bounty as completed.

I have strayed away from creativity. Since the final form should look as the reference image. However, the flexibility is around the randomization algorithm itself for determining the orientation of the image.

**Comment by uneeb123** [comment]
1. the algorithm's input from the prior examples
I share that in the **hints** section

2. the difference between the outputs of the first and second algo permutations
I'm not sure what you are referring to 1st and 2nd. But the final form is an image rendered using p5.js library.

3. how far we can stray with creative freedom for implementing a third permutation?
Flexibility over the algorithm, but the final image should look similar to the reference image

**Comment by cuddle-dev** [comment]
can I take over this issue @uneeb123

**Comment by cuddle-dev** [comment]
@uneeb123  would you be letting me know for environment variables to run it against either mainnet or testnet

**Comment by uneeb123** [comment]
The goerli testnet is deployed at: https://blockalizer-beta.vercel.app/

A few other requirements have changed. We are going to the following controls:

<img width="940" alt="Screenshot 2023-03-30 at 2 40 48 PM" src="https://user-images.githubusercontent.com/4120628/228839604-53d5240b-80d5-48d1-9617-77b90c344221.png">

Additionally we are going to be using the following color schemes:

<img width="847" alt="Screen Shot 2023-03-24 at 2 29 32 PM" src="https://user-images.githubusercontent.com/4120628/228839801-e4b8df21-94be-485a-9037-0e342cfc5c74.png">

Now to answer your questions:

> 1/ do we need to create 6x6 and 9x9 as well (I am asking because I am seeing ui options for that)

Yes, please. There should be various grid sizes.

> 2/ We don't want half circles facing down right?

Correct.

> 4/ would you please let me know .env.example to run it locally? 

Try this:

```
REACT_APP_ALCHEMY_API_KEY=xss-PKzY5OyWxwWFpp5DlMdt-yBMCMI-
REACT_APP_SERVER_URL=https://blockalizer-backend-beta.vercel.app
REACT_APP_BLOCKALIZER_CONTRACT_ADDRESS=0xa83c6a470643416c4001ce01ef0cb94592013b83
REACT_APP_ENV=staging
REACT_APP_AMPLITUDE=somegarbagekey
```

This should connect to the backend that is connected to Goerli testnet

**Comment by 0x4007** [comment]
> A few other requirements have changed. We are going to the following controls:

This should be a separate bounty for several reasons:

1. The bounty hunter agreed to the original scope of work when accepting. Extending scope increases the chance of bounty drop off (non completion.)
2. The DevPool leverages "horizontal scaling" in the form of many talents contributing. Usually all of the bounties can be worked on in parallel which increases development velocity.

**Comment by cuddle-dev** [comment]
> Do you have any updates @0xcodercrane? If you would like to release the bounty back to the DevPool, please comment `/unassign`

Yeah will push my work soon

**Comment by cuddle-dev** [comment]
https://github.com/Alpha-Labs-Global/blockalizer/pull/68
tracking here

**Comment by 0x4007** [comment]
> #68
> tracking here

Be sure to link to the issue in the future.

**Comment by cuddle-dev** [comment]
My ERC20 wallet: 0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46
